name: Release

on:
  create:
    tags:
      - v*.*.*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    steps:
      - uses: actions/checkout@master

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          version: 1.13
        id: go

      - name: Install, Generate, Build
        working-directory: ./backend
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make build
      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAGNAME: ${{ github.event.ref }}
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          GO111MODULE=off go get github.com/tcnksm/ghr
          ghr -n ${TAGNAME} -b "Release ${TAGNAME}" -draft ${TAGNAME} pkg/
